### ISSUE TITLE
What does this Bundler message mean

### ISSUE THREAD

**Issue by jessitron** [gracefuldev/sixmilebridge#16]
hey @avdi what does this mean?

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.

Bundler prints it all day.

**Comment by avdi** [comment]
It means "Avdi, google this warning later and copy and paste something to make it go away" 

—
Avdi Grimm

--- original message ---
On October 3, 2020, 7:04 PM CDT notifications@github.com wrote:



hey @avdi what does this mean?

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java.

Bundler prints it all day.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by jessitron** [comment]
well, that took care of itself

cannot reproduce
